name: tempcord_data_io_generic
description: Implement reading Tempcord file data without platform specific library uses.
version: 1.0.0
environment: 
  sdk: ">=2.16.0 <3.0.0"
homepage: https://github.com/rk0cc/tempcord_data
repository: https://github.com/rk0cc/tempcord_data/tree/main/io_generic
issue_tracker: https://github.com/rk0cc/tempcord_data/issues
dependencies:
  tempcord_data_interface: ^1.1.0
  tempcord_data_parser:
    path: ../parse
dev_dependencies: 
  test: ^1.20.2
dependency_overrides:
  tempcord_data_interface:
    path: ../interface
