name: tempcord_data_parser
description: An abstracted parser implementation for parsing Tempcord data in different platforms.
version: 1.0.0
environment: 
  sdk: ">=2.16.0 <3.0.0"
homepage: https://github.com/rk0cc/tempcord_data
repository: https://github.com/rk0cc/tempcord_data/tree/main/parse
issue_tracker: https://github.com/rk0cc/tempcord_data/issues
dependencies:
  tempcord_data_interface: ">=1.1.0"
  meta: ^1.7.0
  csv: ^5.0.1
  lzma: ^1.0.1
dev_dependencies: 
  test: ^1.20.2
