name: tempcord_data_interface
description: Standarized object model of Tempcord data
version: 1.0.0+1
environment: 
  sdk: ">=2.16.0 <3.0.0"
homepage: https://github.com/rk0cc/tempcord_data
repository: https://github.com/rk0cc/tempcord_data/tree/main/interface
issue_tracker: https://github.com/rk0cc/tempcord_data/issues
dependencies:
  meta: ^1.7.0
  quiver: ^3.0.1+1
dev_dependencies: 
  test: ^1.20.2
